apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.name" . }}
data:
  application.yaml: |
    http:
      server:
        address: ":{{ .Values.service.internalPort }}"
        system:
          address: ":{{ .Values.service.systemPort }}"
    redis:
      address: "{{ template "service.name" . }}-redis:{{ .Values.redis.service.externalPort}}"
      db: {{ .Values.redis.db }}
