apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}-redis
  labels:
    app: {{ template "service.name" . }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    type: microservice
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.externalPort }}
      targetPort: {{ .Values.redis.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "service.name" . }}-redis
