openapi: 3.0.0
info:
  title: Russel Vela's Chatty service
  version: v1
  description: API to communicate in real time with peers
  contact:
    name: Russel Vela
    email: vela.russel@gmail.com
servers:
  - url: localhost/v1
tags:
  - name: Public
    description: public APIs
paths:
  /v1/chatty/signup:
    post:
      summary: Registers a new user
      description: Registers a new user
      operationId: public-post-signup
      tags:
        - Public
      requestBody:
        $ref: '#/components/requestBodies/SignUpRequest'
      responses:
        201:
          $ref: '#/components/responses/201SuccessfulSignUp'
        400:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
  /v1/chatty/token:
    post:
      summary: Returns a token
      description:  Returns a token to be used in further operations
      operationId: public-post-token
      tags:
        - Public
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
      responses:
        200:
          $ref: '#/components/responses/200SuccessfulLogin'
        401:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
  /v1/chatty/users:
    get:
      summary: Returns a list of users
      description: Returns a list of users in Chatty.
      operationId: public-get-users
      tags:
        - Public
      responses:
        200:
          $ref: '#/components/responses/200SuccessGetUsers'
        400:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
  /v1/chatty/chats/ws:
    get:
      summary: Connects to Chatty to send and receive messages
      description: Connects to Chatty
      operationId: public-get-ws
      tags:
        - Public
      responses:
        200:
          $ref: '#/components/responses/200SuccessfulWsConnection'
        400:
          $ref: '#/components/responses/400BadRequest'
        401:
          $ref: '#/components/responses/401UnauthorizedError'
        500:
          $ref: '#/components/responses/500InternalServerError'
      security:
        - jwtAuth: []
  /v1/chatty/channels:
    post:
      summary: Creates a new channel
      description: Creates a new channel
      operationId: public-post-channels
      tags:
        - Public
      requestBody:
        $ref: '#/components/requestBodies/ChannelCreationRequest'
      responses:
        201:
          $ref: '#/components/responses/201SuccessChannelCreation'
        400:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
    get:
      summary: Returns a list of channels
      description: Returns a list of channels in Chatty.
      operationId: public-get-channels
      tags:
        - Public
      responses:
        200:
          $ref: '#/components/responses/200SuccessGetChannels'
        400:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
  /v1/chatty/channels/{id}/subscribe:
    parameters:
      - name: id
        in: path
        description: The id of the channel to subscribe
        required: true
        schema:
          type: string
    post:
      summary: Subscribe to a channel
      description: Subscribe the user invoking this operation to the channel specified by {name}
      operationId: public-post-channels-subscribe
      tags:
        - Public
      requestBody:
        $ref: "#/components/requestBodies/ChannelSubscriptionRequest"
      responses:
        200:
          $ref: '#/components/responses/200SuccessChannelSubscribe'
        400:
          $ref: '#/components/responses/400BadRequest'
        500:
          $ref: '#/components/responses/500InternalServerError'
components:
  requestBodies:
    SignUpRequest:
      description: The request to signup
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignUpSchema'
    LoginRequest:
      description: The request to login
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginSchema'
    ChannelSubscriptionRequest:
      description: The request to subscribe to a new channel
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChannelSubscription'
    ChannelCreationRequest:
      description: The request to create a new channel
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChannelCreation'
  responses:
    201SuccessfulSignUp:
      description: Signup is successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessSignupSchema'
    200SuccessfulLogin:
      description: Login is successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessLoginSchema'
    200SuccessGetUsers:
      description: GetUsers is successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessGetUsers'
    200SuccessGetChannels:
      description: GetChannels is successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessGetChannels'
    200SuccessfulWsConnection:
      description: Message sent successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessWsConnectionSchema'
    200SuccessChannelSubscribe:
      description: Subscribed to channel
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessChannelSubscription'
    201SuccessChannelCreation:
      description: Channel created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessChannelCreation'
    400BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    401UnauthorizedError:
      description: JWT token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedSchema'
    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
  schemas:
    SignUpSchema:
      allOf:
        - $ref: '#/components/schemas/LoginSchema'
    SuccessSignupSchema:
      type: object
      required:
        - username
        - id
      properties:
        ok:
          type: boolean
        username:
          type: string
        id:
          type: string
    LoginSchema:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password
    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
        username:
          type: string
    SuccessGetUsers:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    SuccessLoginSchema:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          format: password
    Channel:
      type: object
      required:
        - id
        - name
        - ownerId
        - visibility
        - members
      properties:
        id:
          type: string
        name:
          type: string
        ownerId:
          type: string
        visibility:
          type: string
        members:
          type: array
          items: {
                   type: string
          }
    SuccessGetChannels:
      type: object
      required:
        - channels
      properties:
        channels:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
    ChannelSubscription:
      type: object
    SuccessChannelSubscription:
      type: object
      required:
        - name
        - ok
      properties:
        name:
          type: string
        ok:
          type: boolean
    ChannelCreation:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
    SuccessChannelCreation:
      type: object
      required:
        - name
        - id
        - ownerId
      properties:
        name:
          type: string
        id:
          type: string
        ownerId:
          type: string
    SuccessWsConnectionSchema:
      type: object
      required:
        - ok
        - timestamp
      properties:
        ok:
          type: boolean
        timestamp:
          type: string
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          default: 0
        message:
          type: string
      required:
        - code
        - message
    UnauthorizedSchema:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
